# Generated by Django 5.0.1 on 2025-06-28 11:42

import django_ckeditor_5.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('artikel', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='artikelblog',
            options={'verbose_name_plural': '2. Artikel'},
        ),
        migrations.AlterModelOptions(
            name='kategori',
            options={'verbose_name_plural': '1. Kategori'},
        ),
        migrations.AlterField(
            model_name='artikelblog',
            name='konten',
            field=django_ckeditor_5.fields.CKEditor5Field(default=0, verbose_name='Text'),
            preserve_default=False,
        ),
    ]
